/**
 * Config Commands
 *
 * Manage backend configuration.
 *
 * Commands:
 *   config sync    Convert .mcp.json to Codex and Gemini formats
 */

import { Command } from 'commander';
import chalk from 'chalk';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

// ============================================================================
// Types
// ============================================================================

interface McpServerConfig {
  type?: string;
  url?: string;
  command?: string;
  args?: string[];
  env?: Record<string, string>;
  headers?: Record<string, string>;
  [key: string]: unknown;
}

interface McpJson {
  mcpServers: Record<string, McpServerConfig>;
}

// ============================================================================
// Format converters
// ============================================================================

/**
 * Convert .mcp.json servers to Codex TOML format.
 * Only emits the [mcp_servers.*] sections.
 */
function toCodexToml(servers: Record<string, McpServerConfig>): string {
  const lines: string[] = [
    '# Generated by `sb mcp sync` from .mcp.json',
    '# Re-run `sb mcp sync` after changing .mcp.json',
    '',
  ];

  for (const [name, config] of Object.entries(servers)) {
    lines.push(`[mcp_servers.${name}]`);

    if (config.url) {
      lines.push(`url = ${tomlString(config.url)}`);
    }

    if (config.command) {
      lines.push(`command = ${tomlString(config.command)}`);
    }

    if (config.args?.length) {
      lines.push(`args = [${config.args.map(tomlString).join(', ')}]`);
    }

    if (config.env && Object.keys(config.env).length > 0) {
      const pairs = Object.entries(config.env)
        .map(([k, v]) => `${tomlString(k)} = ${tomlString(v)}`)
        .join(', ');
      lines.push(`env = { ${pairs} }`);
    }

    if (config.headers) {
      for (const [key, val] of Object.entries(config.headers)) {
        lines.push(`http_headers = { ${tomlString(key)} = ${tomlString(val)} }`);
      }
    }

    lines.push('');
  }

  return lines.join('\n');
}

function tomlString(val: string): string {
  return `"${val.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

/**
 * Convert .mcp.json servers to Gemini settings.json format.
 * Merges into existing settings.json if present.
 */
function toGeminiSettings(
  servers: Record<string, McpServerConfig>,
  existingSettings?: Record<string, unknown>,
): Record<string, unknown> {
  const geminiServers: Record<string, Record<string, unknown>> = {};

  for (const [name, config] of Object.entries(servers)) {
    const server: Record<string, unknown> = {};

    if (config.url) {
      server.url = config.url;
    }

    if (config.command) {
      server.command = config.command;
    }

    if (config.args?.length) {
      server.args = config.args;
    }

    if (config.env && Object.keys(config.env).length > 0) {
      server.env = config.env;
    }

    if (config.headers) {
      server.headers = config.headers;
    }

    geminiServers[name] = server;
  }

  return {
    ...existingSettings,
    mcpServers: geminiServers,
  };
}

// ============================================================================
// Gitignore helper
// ============================================================================

function ensureGitignoreEntries(repoRoot: string, entries: string[]): string[] {
  const gitignorePath = join(repoRoot, '.gitignore');
  const added: string[] = [];

  let content = '';
  if (existsSync(gitignorePath)) {
    content = readFileSync(gitignorePath, 'utf-8');
  }

  const lines = content.split('\n');
  const missing = entries.filter(entry => !lines.some(line => line.trim() === entry));

  if (missing.length > 0) {
    const suffix = content.endsWith('\n') ? '' : '\n';
    const block = `${suffix}\n# Backend-specific config (generated by sb mcp sync)\n${missing.join('\n')}\n`;
    writeFileSync(gitignorePath, content + block);
    added.push(...missing);
  }

  return added;
}

// ============================================================================
// Commands
// ============================================================================

async function syncCommand(): Promise<void> {
  const cwd = process.cwd();
  const mcpPath = join(cwd, '.mcp.json');

  if (!existsSync(mcpPath)) {
    console.error(chalk.red('No .mcp.json found in current directory'));
    process.exit(1);
  }

  let mcpJson: McpJson;
  try {
    mcpJson = JSON.parse(readFileSync(mcpPath, 'utf-8'));
  } catch (err) {
    console.error(chalk.red(`Failed to parse .mcp.json: ${err}`));
    process.exit(1);
  }

  if (!mcpJson.mcpServers || Object.keys(mcpJson.mcpServers).length === 0) {
    console.log(chalk.yellow('No MCP servers found in .mcp.json'));
    return;
  }

  const serverCount = Object.keys(mcpJson.mcpServers).length;
  console.log(chalk.dim(`Found ${serverCount} server(s) in .mcp.json\n`));

  // --- Codex: .codex/config.toml ---
  const codexDir = join(cwd, '.codex');
  const codexPath = join(codexDir, 'config.toml');
  mkdirSync(codexDir, { recursive: true });
  writeFileSync(codexPath, toCodexToml(mcpJson.mcpServers));
  console.log(chalk.green('  wrote'), chalk.cyan('.codex/config.toml'));

  // --- Gemini: .gemini/settings.json ---
  const geminiDir = join(cwd, '.gemini');
  const geminiPath = join(geminiDir, 'settings.json');
  mkdirSync(geminiDir, { recursive: true });

  let existingGemini: Record<string, unknown> | undefined;
  if (existsSync(geminiPath)) {
    try {
      existingGemini = JSON.parse(readFileSync(geminiPath, 'utf-8'));
    } catch { /* overwrite if unparseable */ }
  }

  const geminiSettings = toGeminiSettings(mcpJson.mcpServers, existingGemini);
  writeFileSync(geminiPath, JSON.stringify(geminiSettings, null, 2) + '\n');
  console.log(chalk.green('  wrote'), chalk.cyan('.gemini/settings.json'));

  // --- Gitignore ---
  const added = ensureGitignoreEntries(cwd, ['.codex/', '.gemini/']);
  if (added.length > 0) {
    console.log(chalk.green('  added'), chalk.cyan(added.join(', ')), chalk.green('to .gitignore'));
  }

  console.log(chalk.dim(`\nDone. All backends can now discover MCP servers.`));
}

// ============================================================================
// Register Commands
// ============================================================================

export function registerConfigCommands(program: Command): void {
  const config = program
    .command('config')
    .description('Manage backend configuration');

  config.command('sync')
    .description('Sync .mcp.json to Codex (.codex/config.toml) and Gemini (.gemini/settings.json)')
    .action(syncCommand);
}
